filebeat:
 prospectors:
  -
    paths:
     - "/var/log/messages"
     - "/tmp/echolog"
     - "/tmp/cdtng.log"
     - "/tmp/cdtng_json.log"
     - "/tmp/applogs/*/*.log"

       #output.elasticsearch:
       #hosts: ["http://localhost:9200"]
       #template.enabled: true
       #template.path: "filebeat.template.json"
       #template.overwrite: false
output.logstash:
  hosts: ["localhost:5044"]
