elasticsearch:
  build: elasticsearch/
  environment:
  - ES_JAVA_OPT=""-Xms2g -Xmx2g"
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5044:5044"
  links:
    - elasticsearch
    - redis
redis:
  build: redis/
  mem_limit: 256m
