elasticsearch:
  build: elasticsearch/
  environment:
  - ES_JAVA_OPT=""-Xms2g -Xmx2g"
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
