elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch
    - redis
    - rabbitmq
  privileged: true
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  privileged: true
redis:
  image: redis
  ports:
    - 6379:6379
